### ISSUE TITLE
字体文件缺失

### ISSUE THREAD

**Issue by KanoueShinku** [Kitauji-Sub/Subtitles#1]
[葬送的芙莉莲]字幕op开头部分缺少对应的字体显示不全，字体下载链接也是空的，能否提供一下字体文件？

**Comment by EastonYuu** [comment]
字体包一般是合集出了之后才会把下载链接放上去。
OP 的字体为思源系的 Source Han Serif SC SemiBold 和 Source Han Serif SemiBold ，你可以在 [这里](https://github.com/adobe-fonts) 下载对应的字体。
