### ISSUE TITLE
Duplicate paragraphs in release description

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Kitauji-Sub/Subtitles#11]
This happened in the Matroska variant of the second episode of the *Shoushimin Series* that you released on Bangumi Moe, and three other sites that were automatically released by this site.

Normal on Nyaa.

> 为了您的播放能正确显示字幕效果，我们推荐您观看内封源使用 [MPV 播放器](https://github.com/hooke007/MPV_lazy/releases)，或者挂载 [XySubFilter with libass字幕滤镜](https://github.com/Masaiki/xy-VSFilter/releases)。
> 本组字幕作品基于 [CC BY-NC-ND 4.0 协议](https://creativecommons.org/licenses/by-nc-nd/4.0/) 进行共享。如有需求，可前往北宇治字幕组的[字幕仓库](https://github.com/Kitauji-Sub)下载往期制作的外挂字幕。
> 
> 为了您的播放能正确显示字幕效果，我们推荐您观看内封源使用 [MPV 播放器](https://github.com/hooke007/MPV_lazy/releases)，或者挂载 [XySubFilter with libass字幕滤镜](https://github.com/Masaiki/xy-VSFilter/releases)。
> 
> 本组字幕作品基于 [CC BY-NC-ND 4.0 协议](https://creativecommons.org/licenses/by-nc-nd/4.0/) 进行共享。如有需求，可前往北宇治字幕组的[字幕仓库](https://github.com/Kitauji-Sub)下载往期制作的外挂字幕。

**Comment by EastonYuu** [comment]
Will be fixed in the next episode.
