### ISSUE TITLE
Yorukura: about the title of the first episode

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Kitauji-Sub/Subtitles#14]
I noticed you left it blank in README. Maybe it is because the title is not shown in the anime.

But I noticed that the anime’s official website already has a title: 夜のクラゲ

[第1話｜STORY｜オリジナルTVアニメーション「夜のクラゲは泳げない」公式サイト](https://yorukura-anime.com/story/01.html)

Could you please consider editing the README?

**Comment by EastonYuu** [comment]
Done
