### ISSUE TITLE
败犬女主字幕位置错误

### ISSUE THREAD

**Issue by icytail176** [Kitauji-Sub/Subtitles#15]
只有mkv格式的简日繁内封会出现  在进ed画面前的标题处出现字幕组staff信息的字幕位置靠下和画面内容重合
![微信图片_20240811155305](https://github.com/user-attachments/assets/a6e3c721-1f9b-4e37-8d6a-884f47cb0dc0)

**Comment by scrpr** [comment]
经检查，potplayer、mpv、mpc 等主流播放器均无法复现问题。请在回报问题时提供相关的环境信息，比如播放器类型、版本，系统版本等。

**Comment by icytail176** [comment]
win11 potplayer和mpc都会出现   我朋友的也没有这样的问题 可能是我的问题 我自己看看吧 麻烦了
![微信图片_20240813101413](https://github.com/user-attachments/assets/3cf848d9-cb4c-422a-9373-c8099017c353)

![微信图片_20240813101535](https://github.com/user-attachments/assets/7708834f-c5de-471b-adc8-11d084650beb)

**Comment by scrpr** [comment]
> win11 potplayer和mpc都会出现 我朋友的也没有这样的问题 可能是我的问题 我自己看看吧 麻烦了 ![微信图片_20240813101413](https://private-user-images.githubusercontent.com/174178382/357254653-3cf848d9-cb4c-422a-9373-c8099017c353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTA3ODYsIm5iZiI6MTcyMzU1MDQ4NiwicGF0aCI6Ii8xNzQxNzgzODIvMzU3MjU0NjUzLTNjZjg0OGQ5LWNiNGMtNDIyYS05MzczLWM4MDk5MDE3YzM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMjAxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTQ5ZDAyY2Q2NjE2ZTgwZWIwYjc5OTYzOTBhM2MxOTY2N2Q1NGIwMjczZmU1YzY2ZjMyNjYwM2Q0MTFkNDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IGglXmZ33DKdBH4tB0oeD3zHRqVR0sHCysTvDeryuaw)
> 
> ![微信图片_20240813101535](https://private-user-images.githubusercontent.com/174178382/357254643-7708834f-c5de-471b-adc8-11d084650beb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTA3ODYsIm5iZiI6MTcyMzU1MDQ4NiwicGF0aCI6Ii8xNzQxNzgzODIvMzU3MjU0NjQzLTc3MDg4MzRmLWM1ZGUtNDcxYi1hZGM4LTExZDA4NDY1MGJlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMjAxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWVjOGEzNzhhOTU0Mjc2NGE0ZmM0NGQzMWRiMmY4ZThiNWE4MGJmY2E0YjhhOWE0NDZmZTQwNmQyNTlmMTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FsG2d_fA_kBZqkMR5RiS5KA6pVMRFF4PVn-kMNb4bKc)

考虑到你使用了madvr作为渲染器，请检查madvr设置>processing>AutoSwitch_Profile>zoom control中是否开启了automatically detect hard coded black bars和move subtitles
