### ISSUE TITLE
《葬送的芙莉莲》第10话翻译小错？

### ISSUE THREAD

**Issue by tomtung** [Kitauji-Sub/Subtitles#4]
https://github.com/Kitauji-Sub/Subtitles/blob/ab5d9e3f63afdb5bb611bf58d57a1f6aa44de924/TV/2023/10/Sousou%20no%20Frieren/%5BKitaujiSub%5D%20Sousou%20no%20Frieren%20-%2010.chs_jp.ass#L451

https://github.com/Kitauji-Sub/Subtitles/blob/ab5d9e3f63afdb5bb611bf58d57a1f6aa44de924/TV/2023/10/Sousou%20no%20Frieren/%5BKitaujiSub%5D%20Sousou%20no%20Frieren%20-%2010.chs_jp.ass#L150

「撤退を余儀なくされたが」似乎应直译为「（我们）只能被迫撤退」或者「（我们）不得不撤退」更合适。「只能让他们逃掉」似乎把「撤退」的主体搞错了？

**Comment by EastonYuu** [comment]
感谢报错，我们会在 github 里和合集给予更正。
