### ISSUE TITLE
《葬送的芙莉莲》第1话翻译小错

### ISSUE THREAD

**Issue by tomtung** [Kitauji-Sub/Subtitles#5]
https://github.com/Kitauji-Sub/Subtitles/blob/a534162c5557fff9f3788875fbbe970d0f40de43/TV/2023/10/Sousou%20no%20Frieren/%5BKitaujiSub%5D%20Sousou%20no%20Frieren%20-%2001.chs_jp.ass#L450

https://github.com/Kitauji-Sub/Subtitles/blob/a534162c5557fff9f3788875fbbe970d0f40de43/TV/2023/10/Sousou%20no%20Frieren/%5BKitaujiSub%5D%20Sousou%20no%20Frieren%20-%2001.chs_jp.ass#L172

「タダ酒」里“免费”的意思没有翻译到。直译可能是类似“现在这样也能喝上免费的酒”、“现在这样酒也能免费喝”更确切。

---

https://github.com/Kitauji-Sub/Subtitles/blob/a534162c5557fff9f3788875fbbe970d0f40de43/TV/2023/10/Sousou%20no%20Frieren/%5BKitaujiSub%5D%20Sousou%20no%20Frieren%20-%2001.chs_jp.ass#L652

https://github.com/Kitauji-Sub/Subtitles/blob/a534162c5557fff9f3788875fbbe970d0f40de43/TV/2023/10/Sousou%20no%20Frieren/%5BKitaujiSub%5D%20Sousou%20no%20Frieren%20-%2001.chs_jp.ass#L377

这里没有翻译到「とされています」的“据说…“、”据传…“、”大家认为…“的意思，让这句话变成了海塔自己的断言。

**Comment by EastonYuu** [comment]
后续会对前面的集数重新进行校对，感谢报错

**Comment by tomtung** [comment]
谢谢！我也注意到一些开始有的错误在这个仓库里已经改正过了。当然GitHub本来就是众筹免费劳动力找错改错的社区，所以即使没彻底校对就上传也是正确的打开方式，不用太在意。
