### ISSUE TITLE
文件无法正常下载

### ISSUE THREAD

**Issue by SilianZ** [Kitauji-Sub/Subtitles#7]
`[KitaujiSub] Sousou no Frieren [26][WebRip][HEVC_AAC][CHS_JP&CHT_JP].mkv`

![image](https://github.com/Kitauji-Sub/Subtitles/assets/113701655/05c4ff82-8885-4591-b155-d5be09956d6e)

900多位在线用户凑不出一个完整的文件。

**Comment by EastonYuu** [comment]
问题已经修复完毕，抱歉 orz
