### ISSUE TITLE
Some GitHub links in Subtitle Projects are invalid

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Kitauji-Sub/Subtitles#9]
In *KitaujiSub's Subtitle Projects*, three GitHub links gave `404` errors when accessed.

| Invalid Link | Correct Link |
| :-- | :-- |
| `https://github.com/Kitauji-Sub/Subtitles/blob/main/TV/2022/10/Bocchi%20the%20Rock` | `https://github.com/Kitauji-Sub/Subtitles/tree/main/TV/2022/10/Bocchi%20the%20Rock!` |
| `https://github.com/MingYSub/SubsArchive/blob/main/Archive/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo` | `https://github.com/MingYSub/SubsArchive/tree/main/Archive/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo!` |
| `https://github.com/Kitauji-Sub/Subtitles/blob/main/TV/2023/10/THE%20iDOLM%40STER%20MILLION%20LIVE` | `https://github.com/Kitauji-Sub/subs-imas-million` |

*By the way. Among the remaining GitHub links, some use `blob` and some use `tree`. Could we use the latter uniformly? Because GitHub will automatically redirect to a link containing the latter when accessing a link containing the former.*

**Comment by scrpr** [comment]
We have fixed the usage of `blob` and `tree`, but there's something we can't address.
There are something to do with github projects' url algorithm which would not treat the trailing `!` as a part of the link, such as
`https://github.com/MingYSub/SubsArchive/tree/main/Archive/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo`**!**
`https://github.com/Kitauji-Sub/Subtitles/tree/main/TV/2022/10/Bocchi%20the%20Rock`**!**

Since github projects doesn't support markdown, there is nothing we can do, unless the moderator makes his decision to migrate to other online form services.

**Comment by 3gf8jv4dv** [comment]
> There are something to do with github projects' url algorithm which would not treat the trailing ! as a part of the link

Naruhodo.

<s>So, let’s change our thinking. Could we change the name of the folder? You do not have to pursue a very short folder name (like Nekomoe kissaten), as long as it does not contain such special characters.</s> https://github.com/Kitauji-Sub/Subtitles/issues/9#issuecomment-2233817242

**Comment by 3gf8jv4dv** [comment]
@scrpr @EastonYuu 

Sorry, but I just looked at [*MingYSub Subtitle Overview*](https://github.com/users/MingYSub/projects/1) and they use `%21` instead of `!` in Projects, and GitHub is able to recognize this link. *I should have taken a closer look at their Projects first, sorry :(*

Here are the links they used:

```
https://github.com/MingYSub/SubsArchive/blob/main/Archive/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo%21
```

Considering that the link to this project in *KitaujiSub's Subtitle Projects* has not been changed, is it possible to use this and replace `blob` with `tree`?

**Comment by scrpr** [comment]
> @scrpr @EastonYuu
> 
> Sorry, but I just looked at [_MingYSub Subtitle Overview_](https://github.com/users/MingYSub/projects/1) and they use `%21` instead of `!` in Projects, and GitHub is able to recognize this link. _I should have taken a closer look at their Projects first, sorry :(_
> 
> Here are the links they used:
> 
> ```
> https://github.com/MingYSub/SubsArchive/blob/main/Archive/Kono%20Subarashii%20Sekai%20ni%20Bakuen%20wo%21
> ```
> 
> Considering that the link to this project in _KitaujiSub's Subtitle Projects_ has not been changed, is it possible to use this and replace `blob` with `tree`?

This link has been fixed.
